name: Windows Build - Universal Enhanced  
  
on:  
  push:  
    paths-ignore:  
      - '**.md'  
      - 'docs/**'  
      - 'README*'  
      - 'LICENSE'  
  pull_request:  
    paths-ignore:  
      - '**.md'  
      - 'docs/**'  
      - 'README*'  
      - 'LICENSE'  
  
jobs:  
  build:  
    runs-on: windows-2022  
    timeout-minutes: 90  
  
    steps:  
    - name: Checkout  
      uses: actions/checkout@v4  
      with:  
        submodules: recursive  
        path: src  
  
    - name: Cache vcpkg  
      uses: actions/cache@v4  
      with:  
        path: |  
          C:\vcpkg\installed  
          C:\vcpkg\buildtrees  
        key: vcpkg-v3-${{ hashFiles('src/vcpkg.json') }}  
        restore-keys: vcpkg-v3-  
  
    - name: Cache build directory  
      uses: actions/cache@v4  
      with:  
        path: C:\build  
        key: build-${{ github.ref_name }}-${{ hashFiles('src/**/*.cpp', 'src/**/*.h') }}  
        restore-keys: |  
          build-${{ github.ref_name }}-  
          build-main-  
  
    # Setup sccache CORRIGIDO - usando versão mais recente  
    - name: Setup sccache  
      uses: mozilla-actions/sccache-action@v0.0.5  
  
    - name: Setup vcpkg  
      uses: lukka/run-vcpkg@v11  
      with:  
        vcpkgDirectory: 'C:\vcpkg'  
        vcpkgGitCommitId: '215a2535590f1f63788ac9bd2ed58ad15e6afdff'  
        runVcpkgInstall: true  
  
    - name: Configure CMake  
      run: |  
        cmake -B C:\build -S src -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=Release -DHTTP=ON -DUSE_LUAJIT=OFF -DBUILD_TESTING=OFF -DENABLE_UNITY_BUILD=ON -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DOPENSSL_ROOT_DIR=C:\vcpkg\installed\x64-windows  
      env:  
        VCPKG_ROOT: C:\vcpkg  
  
    - name: Build  
      run: |  
        $cores = if ("${{ github.ref_name }}" -eq "main" -or "${{ github.ref_name }}" -eq "master") { 4 } else { 2 }  
        cmake --build C:\build --config Release --parallel $cores  
  
    - name: Show sccache statistics  
      run: sccache --show-stats  
  
    - name: Validate dependencies  
      run: |  
        $requiredDlls = @("libmariadb.dll")  
        $missingDlls = @()  
          
        foreach ($dll in $requiredDlls) {  
          if (-not (Test-Path "C:\build\Release\$dll")) {  
            $missingDlls += $dll  
          }  
        }  
          
        if ($missingDlls.Count -gt 0) {  
          Write-Warning "Missing DLLs: $($missingDlls -join ', ')"  
        } else {  
          Write-Host "✅ All required dependencies found"  
        }  
  
    - name: Create build info  
      run: |  
        @{  
          branch = "${{ github.ref_name }}"  
          commit = "${{ github.sha }}"  
          build_time = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"  
          vcpkg_commit = "215a2535590f1f63788ac9bd2ed58ad15e6afdff"  
        } | ConvertTo-Json | Out-File "C:\build\Release\build-info.txt"  
  
    - name: Verify and health check  
      run: |  
        if (Test-Path "C:\build\Release\tfs.exe") {  
          Write-Host "✅ Build successful on branch: ${{ github.ref_name }}"  
          $file = Get-Item "C:\build\Release\tfs.exe"  
          Write-Host "File size: $([math]::Round($file.Length/1MB, 2)) MB"  
            
          if ($file.Length -gt 1MB) {  
            Write-Host "✅ Executable appears healthy"  
          } else {  
            Write-Warning "⚠️ Executable seems unusually small"  
          }  
            
          $dlls = Get-ChildItem "C:\build\Release\*.dll" -ErrorAction SilentlyContinue  
          if ($dlls) {  
            Write-Host "📦 Dependencies: $($dlls.Count) DLLs"  
            $dlls | ForEach-Object { Write-Host "  - $($_.Name)" }  
          }  
        } else {  
          Write-Error "❌ Build failed"  
          exit 1  
        }  
  
    - name: Compress artifacts  
      run: |  
        Compress-Archive -Path "C:\build\Release\*" -DestinationPath "C:\build\tfs-release.zip"  
  
    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: tfs-${{ github.ref_name }}-${{ github.sha }}  
        path: C:\build\tfs-release.zip  
        retention-days: 30  
  
    - name: Cleanup build artifacts  
      if: always()  
      run: |  
        Remove-Item -Path "C:\build\CMakeFiles" -Recurse -Force -ErrorAction SilentlyContinue  
        Remove-Item -Path "C:\build\*.tmp" -Force -ErrorAction SilentlyContinue  
  
    - name: Build status summary  
      if: always()  
      run: |  
        Write-Host "🔧 Build Summary for branch: ${{ github.ref_name }}"  
        Write-Host "📅 Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"  
        Write-Host "🔗 Commit: ${{ github.sha }}"  
        if (Test-Path "C:\build\Release\tfs.exe") {  
          Write-Host "✅ Status: SUCCESS"  
        } else {  
          Write-Host "❌ Status: FAILED"  
        }
